### ISSUE TITLE
test builds don't transpile imports from node_modules

### ISSUE THREAD

**Issue by kuhe** [MajorLeagueBaseball/g5-component#6]
If you have

    import { something } from 'es6module/something';

in component code, the babel transform by browserify, such as during the build or watch-js scripts works fine.

The task npm test however, does not pass those imports from node_modules through babel, preventing the test from running. 

This doesn't seem to be specific to babel-tape-runner, since

    mocha --compilers js:babel/register

produced the same result.

I'd appreciate a link to a solution if someone finds a flag or something that works around this. I couldn't google it out.

**Comment by gbabula** [comment]
Brought this up to @substack (the author of tape) a while back - however I have not heard back.
https://twitter.com/gregbabula/status/624632719679614976

Looking in to this, I will keep this thread updated.

**Comment by kuhe** [comment]
I'm not sure if that tweet is about the same issue exactly, but

As suspected ignoring node_modules is default (unchangeable?) behavior. May be able to work around by symlinking.

https://github.com/babel/babelify/issues/44#issuecomment-75134803

As pointed out by @alexmcmillan

**Comment by gbabula** [comment]
Ok so after some investigation I think I have this figured out.

I might need to fork https://github.com/wavded/babel-tape-runner - by default if you use `babel-core/register` (like `babel-tape-runner` does) - node_modules are ignored. To override this functionality, an Object with `ignore: false` has to be passed to `babel-core/register`.

I'll update this ticket once I have a solution set, going to try to get this accomplished without forking babel-tape-runner if possible.

**Comment by gbabula** [comment]
https://github.com/MajorLeagueBaseball/g5-component/commit/1edb544556c590d21ccdeed3b7f03bfd0e88d6c0

Added a .babelrc file with an ignore field - this should work in theory however it appears there is currently a bug with babel.

For the time being, instead of running `npm test` - if your test is importing a ES6 module, simply run this command directly against that file - `babel-node --ignore false test/*.js | tap-spec`.

That is technically doing the same thing as the .babelrc file is supposed to do, hopefully that issue is resolved sooner than later, however according to a lot of people on the Babel team:

> Anything in `node_modules` should already be compiled (e.g. via prepublish script). If it's not, that's a bug with the package you're consuming.
